Changed to support comma separated
pi-hole/web pull request #1290
Opened 2020-05-14 13:04 UTC by stevieboy84

**By submitting this pull request, I confirm the following:** `{please fill any appropriate checkboxes, e.g: [X]}`

`{Please ensure that your pull request is for the 'devel' branch!}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [ ] I have tested my proposed changes.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [X] I have Signed Off all commits. ([`git pu`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**

To resolve bug raised whereby you can't add spaces in Group names:
https://github.com/pi-hole/pi-hole/issues/3335

The bug was introduced by this previous PR:
https://github.com/pi-hole/AdminLTE/pull/1149

This solution only addresses this issue for Groups.  I personally feel that comma delimited lists should be the default over space delimited for other input boxes that were altered in the above mentioned PR, however that is more of an issue to be discussed and agreed by the project owner.

**How does this PR accomplish the above?:**

I've changed the explode function to use a comma delimiter rather than space delimiter for Groups.

**What documentation changes (if any) are needed to support this PR?:**

You may want to mention the ability to add multiple groups in this page of the documentation, however I have set the placeholder text to also imply the behaviour: https://docs.pi-hole.net/database/gravity/example/

2020-05-14 13:08 UTC, PromoFaux commented
Thanks for the submission

> I personally feel that comma delimited lists should be the default over space delimited

I agree with this sentiment, however be aware that one can currently paste a list of items (e.g a list of adlists) and line-breaks are converted to a space. These would need to also be converted to commas.

@pi-hole/core-approvers Does anyone else have any thoughts?

2020-05-14 13:11 UTC, yubiuser commented
> I agree with this sentiment, however be aware that one can currently paste a list of items (e.g a list of adlists) and line-breaks are converted to a space

This is important to remember because a lot of users tend to bulk import adlist URLs they found online. I think they won't be happy (and cause a lot of trouble for pihole's support team) if the behavior would change for adlists and black/whitelists

2020-05-14 13:11 UTC, stevieboy84 commented
> Thanks for the submission
> 
> > I personally feel that comma delimited lists should be the default over space delimited
> 
> I agree with this sentiment, however be aware that one can currently paste a list of items (e.g a list of adlists) and line-breaks are converted to a space. These would need to also be converted to commas.
> 
> @pi-hole/core-approvers Does anyone else have any thoughts?

That's fair.  I've not been able to test this locally.  Is it easy for me to push this code change over to my pi-hole so that I can do some testing against my own device? I had a browse on the filesystem on the pi-hole and couldn't find where the php is stored..

2020-05-14 13:12 UTC, PromoFaux commented
> Is it easy for me to push this code change over to my pi-hole so that I can do some testing against my own device?

Sure, on the pi-hole machine navigate to `/var/www/html/admin` and:

```
sudo git checkout -b stevieboy84-tweak/groups-comma-separated devel
sudo git pull https://github.com/stevieboy84/AdminLTE.git tweak/groups-comma-separated
```

2020-05-14 15:46 UTC, DL6ER requested changes
I disagree with the idea of changing the separator from space to comma. It is important to note that adding space separated items is possible for a (very) long time. I see that you're proposed change is only for the group name, however, we should not have differing behaviors on different pages.

I will put up an alternative solution which may be used to investigate things further. Just mentioning: I have nothing against closing my alternative PR and returning to this one if this is the consensus.

2020-05-14 20:15 UTC, stevieboy84 commented
> I disagree with the idea of changing the separator from space to comma. It is important to note that adding space separated items is possible for a (very) long time. I see that you're proposed change is only for the group name, however, we should not have differing behaviors on different pages.
> 
> I will put up an alternative solution which may be used to investigate things further. Just mentioning: I have nothing against closing my alternative PR and returning to this one if this is the consensus.

I agree that things should be consistent, however I personally disagree that it is obvious behaviour to use spaces as a delimiter

2020-05-16 14:17 UTC, pralor commented
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/bug-creating-group-name-with-spaces-adds-more-than-one-group/32611/2

2020-05-28 19:25 UTC, PromoFaux commented
>I agree that things should be consistent, however I personally disagree that it is obvious behaviour to use spaces as a delimiter

I think, for now at least, we should stick with spaces as that is how it has been since 4.x at least when adding multiple items. I guess it wasn't so obviously noticed before because users didn't have an opportunity to add anything that might contain a space in it!

I will close this PR in favour of #1292, but will add some blurb to the pages to give clear instruction on using them (including removing the confusing placeholder text on the adlist page)

Nevertheless - we greatly appreciate the contribution, and hope this doesn't stop you from making more! :)

2020-05-28 19:25 UTC, closed without merging

2020-06-04 10:31 UTC, stevieboy84 commented
No worries, thanks for considering the PR!