Update daterangepicker
pi-hole/web pull request #1380
Opened 2020-05-25 14:19 UTC by XhmikosR

**By submitting this pull request, I confirm the following:** `{please fill any appropriate checkboxes, e.g: [X]}`

`{Please ensure that your pull request is for the 'devel' branch!}`

- [ ] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [ ] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [ ] I have tested my proposed changes.
- [ ] I am willing to help maintain this change if there are issues with it later.
- [ ] I give this submission freely and claim no ownership.
- [ ] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [ ] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [ ] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

Please check out the individual patches.

1. the update is needed for jQuery 3.x
2. while at it and since there are no minified builds, I added one myself. I know it's a 3rd-party file, but it's in maintenance mode so there aren't and probably won't be a lot of updates. I could add the needed npm scripts for this, but I'd rather keep it simple without adding extra npm dependencies just for this. I mention the exact commands in my commit message. The CSS savings are negligible, so I can revert the CSS minification. The JS savings are quite big, like ~50%
3. I pushed a patch from my fork with a couple of tweaks. These have all been [proposed upstream](https://github.com/dangrossman/daterangepicker/pulls/XhmikosR) too, not sure when or if they will be accepted, but we could wait a bit
4. I pushed a patch to make daterangepicker use the same font as we do everywhere else

2020-05-29 05:07 UTC, XhmikosR commented
I dropped my fork patches, but I don't have high hopes those will be merged upstream anytime soon.

2020-05-29 22:11 UTC, PromoFaux approved these changes

2020-05-29 22:12 UTC, PromoFaux requested changes
@XhmikosR, please resolve merge conflicts

2020-05-30 14:34 UTC, PromoFaux approved these changes

2020-05-30 14:34 UTC, merged