Adding CORS support via environment variable
pi-hole/web pull request #1822
Opened 2021-06-07 10:54 UTC by adyanth

**By submitting this pull request, I confirm the following:** 

- [ X ] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [ X ] I have made only one major change in my proposed changes.
- [ X ] I have commented my proposed changes within the code.
- [ X ] I have tested my proposed changes.
- [ X ] I am willing to help maintain this change if there are issues with it later.
- [ X ] I give this submission freely and claim no ownership.
- [ X ] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [ X ] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [ X ] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**

This adds support for enabling CORS on per host/domain basis
Fixes https://github.com/pi-hole/AdminLTE/issues/1820

**How does this PR accomplish the above?:**

This uses an additional environment variable (introduced in https://github.com/pi-hole/docker-pi-hole/issues/864 and https://github.com/pi-hole/docker-pi-hole/pull/867) to get this list of domains where CORS can be enabled.

**What documentation changes (if any) are needed to support this PR?:**

Need to document the presence and usage of the new environment variable `CORS_HOSTS`.

Ex: `CORS_HOSTS=test.domain.com,example.com`.

> - `{Please delete this quoted section when opening your pull request}`
> - You must follow the template instructions. Failure to do so will result in your issue being closed.
> - Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> - Detail helps us understand an issue quicker, but please ensure it's relevant.

2021-06-15 17:20 UTC, adyanth commented
Bump, Can someone review this?

2021-06-15 21:34 UTC, PromoFaux requested changes
I'm unsure how I feel about this idea overall.

What is stopping you from using `http://pi.hole` instead of your own custom domain name?

2021-06-15 21:34 UTC, PromoFaux commented on scripts/pi-hole/php/auth.php
> +	# Allow user set CORS
tab to spaces please

2021-06-16 04:42 UTC, adyanth commented on scripts/pi-hole/php/auth.php
> +	# Allow user set CORS
Oo had not seen that!

2021-06-16 04:44 UTC, adyanth commented
I have two of them in HA. Which is why I cannot use pi.hole. And I'm using https with a certificate for my lan domain along with my actual domain, both of which can be used to access it (from the internet, protected by SASE).

2021-06-16 05:14 UTC, adyanth commented on scripts/pi-hole/php/auth.php
> +	# Allow user set CORS
Done.

2021-07-04 00:27 UTC, PromoFaux commented
> This may be a vulnerability too? Where an empty origin is always successful in auth.php.

Are you saying that this PR could introduce a vuln?

2021-07-04 04:44 UTC, adyanth commented
> > This may be a vulnerability too? Where an empty origin is always successful in auth.php.
> 
> Are you saying that this PR could introduce a vuln?

Hey @PromoFaux , no, that was referring what I am already using with the traditional install + nginx. That was how I was working around for the CORS issue by setting the host header empty in the PHP environment. Maybe that is a trusted operation, and another discussion altogether.

This PR adds support to set accepted names for the Host header to support FQDN other than pi.hole.

2021-07-04 10:24 UTC, PromoFaux commented
One last check, to make sure I'm not entirely missing something here...

Isn't this what the `VIRTUAL_HOST` env var is used for over on docker?

2021-07-04 10:26 UTC, PromoFaux commented
No, scratch that. I see now.

2021-07-04 10:27 UTC, PromoFaux approved these changes

2021-07-04 10:28 UTC, PromoFaux commented
@DL6ER, Something to keep in mind for API / V6 (description of issue here: https://github.com/bastienwirtz/homer/issues/194)

2021-07-04 10:49 UTC, merged