Added the option for an automatic dark mode based on the device status
pi-hole/web pull request #1836
Opened 2021-06-21 17:46 UTC by AlexLamond

Signed-off-by: = <9060360+AlexLamond@users.noreply.github.com>

**By submitting this pull request, I confirm the following:** `{please fill any appropriate checkboxes, e.g: [X]}`

`{Please ensure that your pull request is for the 'devel' branch!}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [X] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**

`{A detailed description, screenshots (if necessary), as well as links to any relevant GitHub issues}`

This PR adds the ability to set the PiHole theme to auto, enabling users to have light mode when the device is in light mode and dark mode when the device is in dark mode

**How does this PR accomplish the above?:**

`{A detailed description (such as a changelog) and screenshots (if necessary) of the implemented fix}`

The PR adds an additional CSS document that applies the relevant theme on the device theme and adds the option to the themes.php file

**What documentation changes (if any) are needed to support this PR?:**

None

https://user-images.githubusercontent.com/9060360/122794224-4ea43100-d2bc-11eb-9527-89fbf3f5efd5.mov

2021-06-21 17:51 UTC, dschaper commented
The mov isn't working for me but this is a great idea!

2021-06-21 18:04 UTC, AlexLamond commented
> The mov isn't working for me but this is a great idea!

Uploaded an .mp4 that seems to be working now!

2021-06-22 07:19 UTC, DL6ER requested changes
Why `custom-auto` when it is referring to `default` templates? This may cause confusion.

2021-06-22 07:19 UTC, DL6ER commented on scripts/pi-hole/php/theme.php
> +$available_themes["custom-auto"] = array("Pi-hole auto theme (light/dark)", true, "custom-auto");
```suggestion
$available_themes["default-auto"] = array("Pi-hole auto theme (light/dark)", true, "default-auto");
```

And rename `custom-auto.css` to `default-auto.css`

2021-06-22 14:14 UTC, DL6ER approved these changes
Confirmed working with this Firefox debug option:
![Screenshot from 2021-06-22 16-12-39](https://user-images.githubusercontent.com/16748619/122940568-e06f7500-d374-11eb-8ad7-81b8b53b2f58.png)

2021-06-22 14:15 UTC, DL6ER commented
I wonder if we (a) should make this the default choice (can be done in another PR) and (b) when the first user will request the auto theme to be dark**er** ;-)

2021-06-22 14:15 UTC, merged

2021-06-23 16:04 UTC, AlexLamond commented
@DL6ER I considered (a) but wasn't sure if it would be accepted by the userbase or seen as an annoyance and having to go in and set it to specific dark or light? For (b) I'm sure I could find some time to implement a light theme / dark theme dropdown section to choose which one applies in each case. Thoughts?

2021-06-24 09:54 UTC, DL6ER commented
I'm not sure if it'd be seen as an "annoyance". How often do you switch between light and dark? I don't ever switch and use dark throughout the entire day - but this may not be the typical use case.

I wonder how you imagine such a dropdown choice, would it be three drop downs in the end?

1. What to use
  1.1. Always light
   1.2. Always dark
  1.3. Device-dependent

2. Theme to use in light mode
  2.1. There is only one

3. Theme to use in dark mode
  3.1. Midnight
   3.2. Deep-midnight

I do really wonder if it would be worth the effort. We have only one light theme and never had a user submitting a custom theme at all since we have implemented this ability more than one year ago (based on a feature request, btw).

2021-07-04 00:36 UTC, PromoFaux commented
Just something I noticed when reviewing another PR, @AlexLamond - not sure if this is intentional but in auto dark mode the top left background colour remains blue, where the midnight theme is grey

`Pi-hole Midnight theme (dark)`:

![image](https://user-images.githubusercontent.com/1998970/124369823-072c8600-dc68-11eb-9280-f1e34a4d9b7f.png)

`Pi-hole auto theme (light/dark) Windows dark mode`:

![image](https://user-images.githubusercontent.com/1998970/124369832-17dcfc00-dc68-11eb-91dd-313c04626aec.png)

2021-07-04 00:51 UTC, PromoFaux commented
[This was the other PR](https://github.com/pi-hole/AdminLTE/pull/1832) I was reviewing, BTW. I've also noticed that the auto mode does not change the address bar colour on Android chrome, where the manual modes do.:

Default Theme:

![image](https://user-images.githubusercontent.com/1998970/124369924-24158900-dc69-11eb-8f52-a8aacd216182.png)

Midnight Theme:

![image](https://user-images.githubusercontent.com/1998970/124369927-30014b00-dc69-11eb-9d4d-fc6ef28564f3.png)

Deep Midnight:

![image](https://user-images.githubusercontent.com/1998970/124369928-38598600-dc69-11eb-8940-5c62274efddc.png)

Auto (light):

![image](https://user-images.githubusercontent.com/1998970/124369931-47403880-dc69-11eb-8dd9-84586fc25f79.png)

Auto (dark):

![image](https://user-images.githubusercontent.com/1998970/124369940-7060c900-dc69-11eb-918b-5b44ab376f2d.png)