Add delete button to message table
pi-hole/web pull request #1860
Opened 2021-08-08 20:29 UTC by yubiuser

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [x] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**

Adds a delete button to the message table

2021-08-08 20:57 UTC, yubiuser commented
I'm stuck here. Despite using `SQLITE3_OPEN_READWRITE` I always get `While executing message statement: attempt to write a readonly database`

Any ideas how to fix this?

2021-08-09 13:59 UTC, DL6ER requested changes

2021-08-09 13:59 UTC, DL6ER commented on scripts/pi-hole/js/messages.js
> +  utils.showAlert("info", "", "Deleting message # ", id);
```suggestion
  utils.showAlert("info", "", "Deleting message with ID " + parseInt(id, 10), "...");
```

2021-08-09 13:59 UTC, DL6ER commented on scripts/pi-hole/php/message.php
> +
```suggestion
```

No need for a transaction as we're doing only one thing.

2021-08-09 13:59 UTC, DL6ER commented on scripts/pi-hole/php/message.php
> +        }
```suggestion
```

2021-08-09 14:03 UTC, DL6ER commented on scripts/pi-hole/php/message.php
> +if ($_POST['action'] == 'delete_message') {
I forgot one

```suggestion
if ($_POST['action'] == 'delete_message' && isset($_POST['id'])) {
```

2021-08-09 14:05 UTC, DL6ER commented
> Any ideas how to fix this?

Well, the reason is
``` php
$QueriesDB = getQueriesDBFilename();
```
which is `pihole-FTL.db`. However, the web interface of pre-v6.0 has no write permissions to this database file (check the missing group write permission for the `pihole-FTL.db` file):

``` plain
-rw-rw-r-- 1 pihole pihole 8.7M Aug  8 04:41 /etc/pihole/gravity.db
-rw-r--r-- 1 pihole pihole 598M Aug  9 16:00 /etc/pihole/pihole-FTL.db
```

This is, so far, intended and would need a permission change. Note that FTL itself sets these permissions explicitly when creating the database file so the change needs to be done in FTL as well. Let's think about about if this has any bad consequences and, if we agree it does not have any, we can easily add the necessary change to FTL.

2021-08-09 18:39 UTC, yubiuser commented
I see....

What is the risk we are facing? If the web interface can write arbitrary data to the database, we must eliminate the possibility that the data is later interpreted as code but always only displayed as text. 

Messing with existing data should not be a problem - one might loose ones long term history or the network table gets messed up. But nothing should for instance mess with the DNS resolution.

2021-09-11 20:13 UTC, DL6ER commented
@yubiuser Did we address the permission issue somewhere? If so, can you link the related PR?

2021-09-11 21:17 UTC, closed without merging

2021-09-11 22:32 UTC, yubiuser commented
No, we did not address the permissions so far...

2021-09-12 17:45 UTC, yubiuser commented
Follow-up PR https://github.com/pi-hole/AdminLTE/pull/1886