Compromise between new and old colour schemes on Query log
pi-hole/web pull request #1893
Opened 2021-09-16 17:48 UTC by PromoFaux

**By submitting this pull request, I confirm the following:** 

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
**What does this PR aim to accomplish?:**

I'm going to throw a spanner in the works here, been playing about with this as a middle ground using `background-color: rgb(229,83,75,0.1)!important;` for blocked and `background-color: rgb(70,149,74,0.1)!important;` for allowed

![image](https://user-images.githubusercontent.com/1998970/133492694-2c571f82-f956-4799-baac-f171c3b70931.png)

![image](https://user-images.githubusercontent.com/1998970/133492705-f8348780-0c1e-4c5f-881d-3465698cc900.png)

![image](https://user-images.githubusercontent.com/1998970/133492724-cc69f279-ddb3-46b3-b987-943b3c315b84.png)

2021-09-16 18:16 UTC, DL6ER requested changes
`prettier` failed

2021-09-17 12:17 UTC, DL6ER commented
It still fails :upside_down_face: I'll fix it when merging https://github.com/pi-hole/AdminLTE/pull/1888 into this PR.

2021-09-17 12:32 UTC, DL6ER approved these changes

2021-09-17 12:33 UTC, DL6ER commented
@PromoFaux Please give it another look. I replaced the text variable `rowClass = "blocked-row"` by a boolean `blocked` so we need to change it in only one location if we ever need to change something.

2021-09-21 16:38 UTC, dschaper commented
Node test passed, the status is hung up here. 

https://github.com/pi-hole/AdminLTE/actions/runs/1254831670

Okay to merge with admin override.

2021-09-21 16:39 UTC, merged

2021-10-04 05:30 UTC, rdwebdesign commented
@PromoFaux, I have a suggestion:

Applying the CSS rule on <td> tag you can get a better result without using `!important`:

```
.blocked-row td {
  background-color: rgb(229, 83, 75, 0.1);
}

.allowed-row td {
  background-color: rgb(70, 149, 74, 0.1);
}
```