Better pie chart legend
pi-hole/web pull request #2034
Opened 2021-12-28 23:13 UTC by rdwebdesign

**By submitting this pull request, I confirm the following:** 

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [x] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**

This PR improves the pie chart legend.

**How does this PR accomplish the above?:**

Improvements:
- Cleaner legend text (hiding the block color);
- better text wrapping for long series names;
- hover effects and title parameters to the links;

**What documentation changes (if any) are needed to support this PR?:**

none

2021-12-29 19:50 UTC, DL6ER commented
![ezgif-2-01378af22d](https://user-images.githubusercontent.com/16748619/147698396-246f1983-4dab-457a-9a1e-1ec0642d751e.gif)

2022-01-15 17:41 UTC, yubiuser approved these changes, later dismissed

2022-01-15 21:03 UTC, yubiuser requested changes

2022-01-15 21:03 UTC, yubiuser commented on scripts/pi-hole/js/index.js
> +    $("#query-types-legend .eyeConWrapper").click(function (e) {
```suggestion
    $("#query-types-legend .checkboxWrapper").click(function (e) {
```

2022-01-15 21:03 UTC, yubiuser commented on scripts/pi-hole/js/index.js
> +    $("#query-types-legend .eyeConWrapper").click(function (e) {
All the eye needs to be replaced.

2022-01-15 21:37 UTC, rdwebdesign commented on scripts/pi-hole/js/index.js
> +    $("#query-types-legend .eyeConWrapper").click(function (e) {
I will use a different name. 
`checkboxWrapper` is not the right name for this legend box.

`colorboxWrapper` is a better name.

2022-01-16 11:27 UTC, DL6ER commented
Thank you very much. The screenshot in the PR description is outdated, new screenshots:

![Screenshot from 2022-01-16 12-24-09](https://user-images.githubusercontent.com/16748619/149657946-74f9c35b-eb72-42b0-a4e5-b13f2cee62ce.png)
![Screenshot from 2022-01-16 12-25-44](https://user-images.githubusercontent.com/16748619/149657949-de2c8a76-1b77-4ec7-be6b-abae985c0601.png)

With some disabled types:
![Screenshot from 2022-01-16 12-24-45](https://user-images.githubusercontent.com/16748619/149657947-d4c23587-e5d3-44f7-bbba-d20616bd65a4.png)
![Screenshot from 2022-01-16 12-25-57](https://user-images.githubusercontent.com/16748619/149657950-af601c66-582a-4763-8606-670d29420903.png)

2022-01-16 11:29 UTC, DL6ER commented
One things I noticed is that the updates every 60 seconds undo the `hidePieSlice()` action, i.e., if you deselected some types, the periodic update resets this to showing all.

2022-01-16 16:05 UTC, rdwebdesign commented
@DL6ER 

Yes. `setTimeout()` is loading new data and resetting the whole graphic (including the legend). This was happening before, but was hidden until #1996.

I we can solve this in a new PR.

2022-01-16 16:06 UTC, DL6ER approved these changes

2022-01-16 16:49 UTC, yubiuser approved these changes

2022-01-16 16:49 UTC, merged