Add stale cache query status
pi-hole/web pull request #2421
Opened 2022-11-07 13:29 UTC by DL6ER

## Thank you for your contribution to the Pi-hole Community!

Please read the comments below to help us consider your Pull Request.

We are all volunteers and completing the process outlined will help us review your commits quicker.

**Please make sure you**

 1. Base your code and PRs against the repositories developmental branch.
 2. [Sign Off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits as we enforce the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
 3. [Sign](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all your commits as they must have verified signatures
 4. File a pull request for any change that requires changes to [our documentation](https://docs.pi-hole.net/) at our [documentation repo](https://github.com/pi-hole/docs) 

---

**What does this PR aim to accomplish?:**

See title

To be able to review this PR, you have to:
1. Run FTL on branch `update/dnsmasq` (https://github.com/pi-hole/FTL/pull/1469)
2. Add `use-stale-cache` to any of your `*.conf` files in `/etc/dnsmasq.d/`

An example of what you will see:

![Screenshot 2022-11-07 at 14-14-10 Pi-hole - ryzen](https://user-images.githubusercontent.com/16748619/200321494-02be7ad8-82a1-4a31-94d9-37fd47aec0f1.png)

The green box at the end shows the first queries to this domain (it is frequently queried as long as you have https://discourse.pi-hole.net/ open). Notice the almost 100 msec delay. This domain has a particularly small TTL making it an ideal test case for this.

Typically, once the query expired (orange box), it'd have to be forwarded again, causing an additional delay of (again) roughly 100ms until the reply arrived and can be forwarded to the client. However, with `use-stale-cache`, FTL instead *immediately* replies with the "old" data and does a lookup of this domain in the background (not logged). You see that subsequent queries are again served from cache as usual as the background lookup already succeeded. If it would not have arrived, FTL would again serve stale data from cache and retried the cache-refreshing lookup.

**How does this PR accomplish the above?:**

Add interpretation of the new query status 17

**Link documentation PRs if any are needed to support this PR:**

TBD

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
3. I have commented my proposed changes within the code and I have tested my changes.
4. I am willing to help maintain this change if there are issues with it later.
5. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
6. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
7. I have checked that another pull request for this purpose does not exist.
8. I have considered, and confirmed that this submission will be valuable to others.
9. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
10. I give this submission freely, and claim no ownership to its content.

---
- [X] I have read the above and my PR is ready for review. *Check this box to confirm*

2022-11-08 19:34 UTC, rdwebdesign requested changes

2022-11-08 19:34 UTC, rdwebdesign commented on db_queries.php
> +                            <div><input type="checkbox" id="type_cached" checked><label for="type_cached_stale">Permitted: stale cache</label></div>
You added 2 items with the same ID. You need to change the second one:
```suggestion
                            <div><input type="checkbox" id="type_cached" checked><label for="type_cached">Permitted: cached</label></div>
                            <div><input type="checkbox" id="type_cached_stale" checked><label for="type_cached_stale">Permitted: stale cache</label></div>
```

2022-11-09 20:16 UTC, rdwebdesign approved these changes, later dismissed

2022-11-09 21:24 UTC, yubiuser requested changes
Need to be added here (excluded), otherwise they will count as exact blocked

https://github.com/pi-hole/AdminLTE/blob/57fd6b7adcf5a4b5a21eb784e370c68fbbc794d8/scripts/pi-hole/js/db_queries.js#L183

2022-11-09 21:38 UTC, rdwebdesign commented
> Need to be added here (excluded), otherwise they will count as exact blocked
> 
> https://github.com/pi-hole/AdminLTE/blob/57fd6b7adcf5a4b5a21eb784e370c68fbbc794d8/scripts/pi-hole/js/db_queries.js#L183

Or on the next line (cached):

https://github.com/pi-hole/AdminLTE/blob/57fd6b7adcf5a4b5a21eb784e370c68fbbc794d8/scripts/pi-hole/js/db_queries.js#L185

2022-11-09 21:41 UTC, yubiuser commented
Interestingly, `statistics[1]`

https://github.com/pi-hole/AdminLTE/blob/57fd6b7adcf5a4b5a21eb784e370c68fbbc794d8/scripts/pi-hole/js/db_queries.js#L185-L186

Is never used. Maybe we need to revise our percentage calculation.

2022-11-09 21:42 UTC, rdwebdesign commented
Do we need to include status 17 here?

https://github.com/pi-hole/AdminLTE/blob/c2afe4221ac275a1c082e1d8e14ccbb6113b0e7b/api_db.php#L194-L195

2022-11-11 21:35 UTC, yubiuser commented
Needs rebase.

2022-11-14 18:03 UTC, DL6ER commented
Rebase done. Sorry, I missed your message @yubiuser

2022-11-14 18:04 UTC, yubiuser approved these changes

2022-11-14 18:06 UTC, rdwebdesign approved these changes

2022-11-14 18:06 UTC, merged