Add a parameter to pidofFTL() function to allow a delay when necessary
pi-hole/web pull request #2511
Opened 2023-01-23 18:53 UTC by rdwebdesign

### What does this PR aim to accomplish?

This PR tries to fix a behavior affecting some installations (docker and bare metal) where the web interface button "Restart DNS resolver" causes an apparent error, while restarting FTL.

This topic from Discourse shows the problem on a bare metal install:
https://discourse.pi-hole.net/t/restart-dns-resolver-is-killing-new-ftl/60693/25

The real issue:
FTL is restarted, but in some cases the PHP page is reloaded before FTL is completely restarted. 
The page uses the function `pidofFTL()` to read the PID, but the value is not found and _"FTL is offline"_ message is shown.

A few milliseconds after that, FTL finishes the restart process.

Screen capture showing the behavior:
![restart_FTL_issue](https://user-images.githubusercontent.com/1385443/214122562-14986b4a-151f-436d-9c16-3afd8c14f611.gif)

### How does this PR accomplish the above?

Adding a small delay to `pidofFTL()` function fixes the problem.

### Link documentation PRs if any are needed to support this PR

none

---

**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [x] I have read the above and my PR is ready for review. *Check this box to confirm*

2023-01-23 19:14 UTC, DL6ER commented
> FTL is restarted, but in some cases the PHP page is reloaded before FTL is completely restarted.

To me this sounds like the real fix would rather be delaying the reload. This is what others do, too, for instance my router: when I click on the restart button, it shows some 10 seconds countdown before it allows any further actions on the page. The countdown is ticking down so users don't get impatient thinking that maybe nothing is happening and something has frozen.

Mind that FTL may need longer than one second to restart on low end services with very many queries within 24 hours a it has to reload then after a restart.

2023-01-23 19:24 UTC, rdwebdesign commented
Well, this is actually delaying the reload, but only for a few milliseconds.

Reading your comment, I think we could simply add a third state.

The current PHP page shows 2 states:
- FTL service is offline (in case no PID is found) or
- the normal page with all values.

We could introduce a new state using a message "FTL is restarting...".

2023-02-15 21:52 UTC, yubiuser requested changes

2023-02-15 21:52 UTC, yubiuser commented on scripts/pi-hole/js/restartdns.js
> +var counterMsg = "FTL is reoaling: ";
```suggestion
var counterMsg = "FTL is reloading: ";
```

2023-02-15 21:52 UTC, yubiuser commented on settings.php
> +$FTLpid = intval(pidofFTL($FTLrestarted));
I'm not sure if I understand what your are doing here. Why are your passing `$FTLrestarted` to `pidofFTL()`. That function does not make use of passed argements.

2023-02-15 21:58 UTC, rdwebdesign commented on settings.php
> +$FTLpid = intval(pidofFTL($FTLrestarted));
I need to remove this.

My first attempt was change `pidofFTL()` to add a delay if `$FTLrestarted` was true, but I changed the whole idea and forgot to remove this from the code.

2023-04-12 17:50 UTC, rdwebdesign commented
Branch was updated.

2023-04-14 13:15 UTC, yubiuser approved these changes

2023-04-15 16:06 UTC, merged