Add zooming on the dashboard's two main graphs
pi-hole/web pull request #2807
Opened 2023-11-05 20:43 UTC by DL6ER

# What does this implement/fix?

Add zooming on the dashboard's two main graphs. You can zoom either with [Ctrl] + your mouse wheel (desktop) or the multi-touch "pinch" gesture (mobile). You can then drag with a single click (or finger) to move the graph up or down in case zooming wasn't that accurate.

This feature comes in handy when you have spikes in your dashboard that render the graphs useless, otherwise, see this example (screenshots from a mobile device):

![normal](https://github.com/pi-hole/web/assets/16748619/03ad8c1e-157a-4be2-bee0-d80621e85a01)

![zoomed](https://github.com/pi-hole/web/assets/16748619/c9c28514-a324-48e0-8a24-e21f27646387)

---

**Related issue or feature (if applicable):** N/A

**Pull request in [docs](https://github.com/pi-hole/docs) with documentation (if applicable):** N/A

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

## Checklist:

- [x] The code change is tested and works locally.
- [x] I based my code and PRs against the repositories `developmental` branch.
- [x] I [signed off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
- [x] I [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all my commits. Pi-hole requires signatures to verify authorship
- [x] I have read the above and my PR is ready for review.

2023-11-06 18:51 UTC, PromoFaux commented
I appear to be able to only zoom in one direction, no matter which way I turn the scroll wheel on my mouse.

2023-11-07 17:44 UTC, rdwebdesign requested changes

2023-11-07 17:44 UTC, rdwebdesign commented on scripts/pi-hole/js/index.js
> +        if (!chart.absMax) chart.absMax = chart.scales.y.max;
When I zoom in the zoom speed seems to be normal, but when I try to zoom out the scale changes slowly, in very small steps:

![slow_zoom_out](https://github.com/pi-hole/web/assets/1385443/412697ad-7c96-4baa-a9ed-0ca2a1755a67)

Changing the code to use the original max bound (70 in my example) seems to fix this:

```suggestion
        // The first time the chart is zoomed, save the maximum initial scale bound
        if (!chart.absMax) chart.absMax = chart.getInitialScaleBounds().y.max;
```

2023-11-07 18:14 UTC, DL6ER commented on scripts/pi-hole/js/index.js
> +        if (!chart.absMax) chart.absMax = chart.scales.y.max;
I did not know such a function exists

2023-11-07 18:38 UTC, rdwebdesign approved these changes

2023-11-07 19:56 UTC, merged