Loca records: better layout to avoid text overlapping in smaller screens
pi-hole/web pull request #2864
Opened 2023-11-21 23:34 UTC by rdwebdesign

### What does this PR aim to accomplish?

Second part of #2854 fix.
Avoid text overlapping in smaller screens.

### How does this PR accomplish the above?*

Using a single column in medium and small screens. Only use 2 columns in large screens.
Small adjustments to grid holding the datatables control elements.

### Link documentation PRs if any are needed to support this PR:

none

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [x] I have read the above and my PR is ready for review. *Check this box to confirm*

2023-11-22 07:15 UTC, yubiuser requested changes
It's to narrow in boxed layout

![Screenshot at 2023-11-22 08-14-40](https://github.com/pi-hole/web/assets/26622301/4f1b58f7-4173-4c3c-bbb9-d63cdf82c2dc)
![Screenshot at 2023-11-22 08-14-52](https://github.com/pi-hole/web/assets/26622301/1c4ec314-358e-40d4-99a0-53a9b8275219)

2023-11-22 07:15 UTC, yubiuser commented on settings-dnsrecords.lp
> +                                        <input id="Hdomain" type="url" class="form-control" data-configkeys="hosts" placeholder="Add a domain (example.com or sub.example.com)" autocomplete="off" spel
```suggestion
                                        <input id="Hdomain" type="url" class="form-control" data-configkeys="hosts" placeholder="Domain" autocomplete="off" spellcheck="false" autocapitalize="none" autocorrect="off">
```

2023-11-22 07:15 UTC, yubiuser commented on settings-dnsrecords.lp
> +                                        <input id="Hip" type="text" class="form-control" data-configkeys="hosts" placeholder="Associated IP address" autocomplete="off" spellcheck="false" autocapitali
```suggestion
                                        <input id="Hip" type="text" class="form-control" data-configkeys="hosts" placeholder="Associated IP" autocomplete="off" spellcheck="false" autocapitalize="none" autocorrect="off">
```

2023-11-22 07:15 UTC, yubiuser commented on settings-dnsrecords.lp
> +                                        <input id="Cdomain" type="url" class="form-control" data-configkeys="cnameRecords" placeholder="Add a domain (example.com or sub.example.com)" autocomplete="of
```suggestion
                                        <input id="Cdomain" type="url" class="form-control" data-configkeys="cnameRecords" placeholder="Domain" autocomplete="off" spellcheck="false" autocapitalize="none" autocorrect="off">
```

2023-11-22 07:15 UTC, yubiuser commented on settings-dnsrecords.lp
> +                                        <input id="Ctarget" type="url" class="form-control" data-configkeys="cnameRecords" placeholder="Associated Target Domain" autocomplete="off" spellcheck="false"
```suggestion
                                        <input id="Ctarget" type="url" class="form-control" data-configkeys="cnameRecords" placeholder="Target Domain" autocomplete="off" spellcheck="false" autocapitalize="none" autocorrect="off">
```

2023-11-22 21:58 UTC, rdwebdesign commented
What do you think about this?

![image](https://github.com/pi-hole/web/assets/1385443/dd5113d9-e2e3-4f52-a7a7-418f6244d585)

2023-11-22 22:16 UTC, rdwebdesign commented on settings-dnsrecords.lp
> +                                        <input id="Hdomain" type="url" class="form-control" data-configkeys="hosts" placeholder="Add a domain (example.com or sub.example.com)" autocomplete="off" spel
Done

2023-11-22 22:16 UTC, rdwebdesign commented on settings-dnsrecords.lp
> +                                        <input id="Hip" type="text" class="form-control" data-configkeys="hosts" placeholder="Associated IP address" autocomplete="off" spellcheck="false" autocapitali
Done

2023-11-22 22:16 UTC, rdwebdesign commented on settings-dnsrecords.lp
> +                                        <input id="Cdomain" type="url" class="form-control" data-configkeys="cnameRecords" placeholder="Add a domain (example.com or sub.example.com)" autocomplete="of
Done

2023-11-22 22:17 UTC, rdwebdesign commented on settings-dnsrecords.lp
> +                                        <input id="Ctarget" type="url" class="form-control" data-configkeys="cnameRecords" placeholder="Associated Target Domain" autocomplete="off" spellcheck="false"
Done

2023-11-23 06:27 UTC, rdwebdesign commented
I saw a small intermittent glitch when during the tests. 

If I reload the page many times, sometimes the column widths are not correct (see the column with the button):

![image](https://github.com/pi-hole/web/assets/1385443/4c0b78f7-5c19-48ed-bced-21692c508b51)

Looking at the browser console, the columns width were set to zero on the first table (the one showing the issue).
I think the table is drawn before the Datatables calculates the column widths.
The widths are fixed if the windows is manually resized. Using `.columns.adjust().draw()` did not fix the issue.

Adding `autoWidth: false` fixed the issue:

![image](https://github.com/pi-hole/web/assets/1385443/affc506b-6cb4-4cff-ae46-24426ea24a62)

2023-11-23 20:02 UTC, yubiuser approved these changes

2023-11-23 20:10 UTC, merged