Tweak settings level and add changed-only toggle
pi-hole/web pull request #2882
Opened 2023-11-29 12:15 UTC by DL6ER

# What does this implement/fix?

Remove settings level selection in favor of a simple settings level toogle in the same place:

![Screenshot from 2023-11-29 13-13-53](https://github.com/pi-hole/web/assets/16748619/704bfc89-a5fd-41f2-bc49-33f2e4faafcb)
![Screenshot from 2023-11-29 13-13-55](https://github.com/pi-hole/web/assets/16748619/7c8db1ec-1d1c-4cc0-ac8c-abab36560a86)

Furthermore, we add a feature requested on Discourse: A toggle in the empty place on the `All settings` page that allows you to hide all default-valued config options:

![Screenshot from 2023-11-29 13-14-21](https://github.com/pi-hole/web/assets/16748619/ca1f2638-a359-4c36-9d9f-23bf6e37d6b0)
![Screenshot from 2023-11-29 13-14-24](https://github.com/pi-hole/web/assets/16748619/157f7083-6874-401d-92c1-6d34e6a07f04)

---

**Related issue or feature (if applicable):** N/A

**Pull request in [docs](https://github.com/pi-hole/docs) with documentation (if applicable):** N/A

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

## Checklist:

- [x] The code change is tested and works locally.
- [x] I based my code and PRs against the repositories `developmental` branch.
- [x] I [signed off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
- [x] I [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all my commits. Pi-hole requires signatures to verify authorship
- [x] I have read the above and my PR is ready for review.

2023-11-29 12:45 UTC, DL6ER commented
Changed the color in the last commit to match the icon color:

![grafik](https://github.com/pi-hole/web/assets/16748619/5e70e364-756f-494b-b8a4-9d2e4e74ffaf)

2023-11-30 20:25 UTC, yubiuser requested changes
![Screenshot at 2023-11-30 21-25-13](https://github.com/pi-hole/web/assets/26622301/87592ef4-f0c6-4c06-89bd-bff7f257d60e)

2023-11-30 21:20 UTC, yubiuser submitted a review, later dismissed
![Peek 2023-11-30 22-14](https://github.com/pi-hole/web/assets/26622301/40faf986-7ee4-47d3-b7a7-ed63bf0b0888)

Switching to "All settings" sets the level to basic and no items are shown.

2023-11-30 21:22 UTC, yubiuser reviewed
Suggesting

`settings.js` L44 to change `title="This is an advanced level setting` to `title="This is an expert level setting`

2023-11-30 21:25 UTC, rdwebdesign commented
> `title="This is an expert level setting"`

Maybe we should remove the "This is" part and use only `title="Expert level setting"`.

2023-12-01 03:21 UTC, rdwebdesign requested changes

2023-12-01 03:21 UTC, rdwebdesign commented on style/pi-hole.css
> +.settings-level-expert {
Now there are 2 identical definitions for `settings-level-expert`.
We only need one.

2023-12-01 04:07 UTC, rdwebdesign requested changes

2023-12-01 04:07 UTC, rdwebdesign commented on settings-all.lp
> +<div class="row settings-level-expert" id="advanced-content">
I don't think we need this class here.

```suggestion
<div class="row" id="advanced-content">
```

This is probably the reason the page is empty on yubi's screenshot.

2023-12-01 08:42 UTC, DL6ER commented on settings-all.lp
> +<div class="row settings-level-expert" id="advanced-content">
This is intended. The page should not show anything if on *basic* level - a user may still get there from a link they found somewhere. The issue @yubiuser has seen is to be fixed elsewhere

2023-12-01 09:05 UTC, DL6ER commented
When users decide to manually browse to https://pi.hole/admin/settings/all they will see:

![Screenshot from 2023-12-01 10-02-09](https://github.com/pi-hole/web/assets/16748619/798b5f64-e597-45c1-94e7-f216325892be)

2023-12-01 18:13 UTC, rdwebdesign commented
Sending users to a different page and then back doesn't seem like the best solution. It's a bit of a bad user experience.

Suggestions - If this page is accessed using basic level:

1. show the level toggle or
2. do not allow and redirect to /settings/system or /index
3. automatically set Expert level (this is not an access level intended to block users without permissions, it is just a way to simplify the settings pages (view level). The user can already change the level whenever they wish).

2023-12-01 18:15 UTC, DL6ER commented
You have to consider that nobody may ever see this. It's the edge case of the edge case 

To me no. 2 sounds best, least obscure behavior in contrast to magically changing  boxes or silent settings changes

2023-12-02 01:13 UTC, rdwebdesign submitted a review, later dismissed

2023-12-02 13:30 UTC, yubiuser reviewed
Some items lost/miss the "expert level" icon:

DNS/Conditional forwarding
Web/Exclusions
Web/Active sessions
Privacy/Privacy level

What shall we do with boxes that are no "settings" (don't allow interactions) but are also not shown in "basic" (eg. some boxes in system) - shall they get an icon?

2023-12-02 17:15 UTC, DL6ER commented
So far, the settings levels (now reduced to two) were set in the web interface along - independently of FTL's flag `ADVANCES_SETTING`. This should probably be brought together *somehow*. I'm not sure how to do this best without the boxes first appearing and then disappearing again (or the other way around) as the AJAX API call will in every case have some (even it small) delay. Ideas?

2023-12-02 17:51 UTC, rdwebdesign commented
I think hiding every box by default and showing after the AJAX call is a better option.

2024-01-07 11:17 UTC, yubiuser commented
@DL6ER 

Should we reopen this?

2024-01-07 13:23 UTC, DL6ER commented
> I think hiding every box by default and showing after the AJAX call is a better option.

I played with this and it is not actually straight-forward as the web interface is grouping settings that belong together into a box whereas the settings themselves (and hence the `advanced: yes|no' flag) are completely independent of one another at FTL level. So maybe some code that shows a box if it contains *at least* one item we show? But how do we deal with hints/notes in these boxes? They somehow have to be assigned to certain items then, too.

This all looks like getting everything really complicated which is also why I haven't had the time to work on this further after the last comments - and which eventually lead to the PR being considered abandoned (it effectively was).

How do we proceed? @yubiuser @rdwebdesign

2024-01-07 17:29 UTC, yubiuser commented
I think this PR is a nice addition by reducing the overall number of "levels" and adding the "show only changed" items. This is worth to be implemented. In a subsequent step, we can think about how to deal with the "doubled" FTL and web flags and how/if we could combine them.

2024-01-08 21:11 UTC, yubiuser commented
We should use the same symbols for "expert level" boxes on the the settings pages (currently wrench) and in "all settings" (cog)

2024-01-08 21:29 UTC, yubiuser commented
1. We still have a  few mixture of "advanced" and "expert" across various files. This should be unified.
2. We decided to call it "settings-all" > this should be reflected also by renaming "settings-advanced.js" to "settings-all.js"

2024-01-08 21:46 UTC, yubiuser commented
Thinking about 

>  In a subsequent step, we can think about how to deal with the "doubled" FTL and web flags and how/if we could combine them.

Why do we need this FTL flag at all? We currently use it in two places: on various setting pages to determine if at least one "setting" within a "box" has the flag and set the wrench symbol. And on "all settings" to set the cog symbol for each setting box. 

My proposal: remove the flag entirely. On the setting page, manually set the wrench to the box if we think the box contains something considered "advanced/expert". On "all settings" this symbol is useless > "all settings" is only reachable if "Expert level" has been selected already. If a user is so advanced to play around in "all settings" there is no need to highlight some settings as "advanced"

2024-02-11 09:17 UTC, DL6ER commented
The last comment makes this PR depend on https://github.com/pi-hole/FTL/pull/1883

2024-03-08 19:32 UTC, PromoFaux commented
Tested (both PRs) and working well. A couple of comments from my perspective (by no means mandatory for approval and up for discussion/refusal!)

On the All Settings page, after toggling to show only modified settings, the group headers are still visible if there are no modified settings within that group. Could those also be removed?

On the Local DNS Settings page (which is only visible with the Expert mode toggled), if you toggle the switch back to basic, you are left on the Local DNS Settings page but with zero options. Could a redirect to System be implemented in this case?

2024-03-15 03:52 UTC, rdwebdesign commented
When the page is loaded, the checkbox is visible before the toggle buttons are created:

![checkbox](https://github.com/pi-hole/web/assets/1385443/b5b7cdcd-77c6-4da4-b22a-0f7031826b8b)

I'm adding a commit to hide it using CSS.

2024-03-17 17:59 UTC, rdwebdesign approved these changes

2024-03-17 19:35 UTC, merged