Auto resize some textarea fields
pi-hole/web pull request #2998
Opened 2024-04-01 18:06 UTC by DL6ER

# What does this implement/fix?

Implements auto resizing for selected `<textarea>` input fields

>[!NOTE]
> This feature is *brand new* and requires an up-to-date browser. To date, only Chrome 123.0+ supports this.

Examples:
![0](https://github.com/pi-hole/web/assets/16748619/3046093b-ac05-4fcf-acc8-9fff3cea798a)
![1](https://github.com/pi-hole/web/assets/16748619/134ff2b3-4334-4f77-8821-23c794788313)
![many](https://github.com/pi-hole/web/assets/16748619/a94ef6da-4f81-41d4-8ead-f5067c6b6893)

![regex](https://github.com/pi-hole/web/assets/16748619/e5cdf9f7-d46f-4c31-96bc-ee8d536b1b65)

![1](https://github.com/pi-hole/web/assets/16748619/00b8c503-3096-4902-94d2-1254c4f7eb10)
![2](https://github.com/pi-hole/web/assets/16748619/07bbbf9a-8011-4f2a-ba3c-eca66fd59ac8)
![3](https://github.com/pi-hole/web/assets/16748619/d75a4935-cec5-471b-bfdb-ef0f67c644bd)

There is some protection installed to ensure fields can neither get too small...

![Screenshot from 2024-04-01 19-54-44](https://github.com/pi-hole/web/assets/16748619/d36621e6-cc9e-4e7f-be3a-db23a161c7c8)

... nor too large (scrolling is enabled in this case):

![Screenshot from 2024-04-01 19-55-50](https://github.com/pi-hole/web/assets/16748619/28b860af-6eb5-4196-bd9c-ca8c39660ece)

----

**Related issue or feature (if applicable):** N/A

**Pull request in [docs](https://github.com/pi-hole/docs) with documentation (if applicable):** N/A

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

## Checklist:

- [x] The code change is tested and works locally.
- [x] I based my code and PRs against the repositories `developmental` branch.
- [x] I [signed off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
- [x] I [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all my commits. Pi-hole requires signatures to verify authorship
- [x] I have read the above and my PR is ready for review.

2024-04-01 19:15 UTC, rdwebdesign commented
I'm not sure if we should limit the width using `max-inline-size`. 

The current layout uses `width: 100%` for other form elements.

2024-04-02 08:08 UTC, DL6ER commented
Where would we need ultra-wide textarea inputs? I have no objections against removing parts of the defensive CSS if they are breaking something. The rules are there to prevent odd results with extremely long inputs like you could have in `dns.hosts` for records IPv6 + very long hostnames, etc.

2024-04-02 16:19 UTC, rdwebdesign commented
> Where would we need ultra-wide textarea inputs?

That's not the issue, but we would have screen sizes where every form element will take 100% of its parent container, except these textarea elements, breaking the layout.

> The rules are there to prevent odd results with extremely long inputs like you could have in `dns.hosts` for records IPv6 + very long hostnames, etc.

We currently have `width: 100%`. 
With this rule, form elements won't be wider than their containers. Long lines will simply break inside the textarea.

2024-04-02 18:29 UTC, DL6ER commented on style/pi-hole.css
> +  max-inline-size: 50ch;
```suggestion
```

2024-04-02 18:37 UTC, rdwebdesign requested changes

2024-04-02 18:37 UTC, rdwebdesign commented on style/pi-hole.css
> +  max-block-size: 20rlh;
```suggestion
```

Removing `max-block-size` will allow the textarea to grow just like the other input fields (form elements are using `width: 100%`).

2024-04-02 18:48 UTC, rdwebdesign approved these changes

2024-04-02 19:21 UTC, merged