Show warning if user already set an application password
pi-hole/web pull request #3048
Opened 2024-06-15 09:27 UTC by DL6ER

# What does this implement/fix?

See title.

### No app password is set

![Screenshot from 2024-06-15 11-23-25](https://github.com/pi-hole/web/assets/16748619/2af5e323-a88a-4d3b-96eb-e8f2071cdffc)

### App password is already set

![Screenshot from 2024-06-15 11-22-25](https://github.com/pi-hole/web/assets/16748619/d97b2861-73b7-4580-aa09-f5155285c25b)

---

**Related issue or feature (if applicable):** N/A

**Pull request in [docs](https://github.com/pi-hole/docs) with documentation (if applicable):** N/A

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

## Checklist:

- [x] The code change is tested and works locally.
- [x] I based my code and PRs against the repositories `developmental` branch.
- [x] I [signed off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
- [x] I [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all my commits. Pi-hole requires signatures to verify authorship
- [x] I have read the above and my PR is ready for review.

2024-06-15 11:21 UTC, yubiuser commented
This is a nice idea. I only fear that the hint is not strong enough. Could we have this warning as a preceding modal that allows to cancel or proceed (to the actual app password modal) and requires an active click to continue?

2024-06-15 17:53 UTC, rdwebdesign approved these changes, later dismissed

2024-06-15 18:16 UTC, rdwebdesign requested changes

2024-06-15 18:16 UTC, rdwebdesign commented on settings-api.lp
> +                <div class="danger-area" style="display: none;" id="existing_apppw_warning">
As an alternative to yubi's suggestion, we could use a different style for the warning box, using a different CSS classes:

```suggestion
                <div class="callout callout-warning" style="display: none;" id="existing_apppw_warning">
```

---

We also need to remove lines 25 to 27 from `default-dark.css` theme _(or change its color to `#fff`)_:
https://github.com/pi-hole/web/blob/3681d7187a44b32a667f40b585629d45bf4e44e9/style/themes/default-dark.css#L25-L27

![image](https://github.com/pi-hole/web/assets/1385443/03c80300-0336-4ea4-b6be-158e9a0d9812)

2024-06-17 19:29 UTC, rdwebdesign commented
Screenshots:

![image](https://github.com/pi-hole/web/assets/1385443/8713219d-cd93-4634-b52d-552520b575e8)

2024-06-25 20:26 UTC, yubiuser requested changes
On midnight and high contrast dark theme the cross is hard to see

![Screenshot at 2024-06-25 22-21-39](https://github.com/pi-hole/web/assets/26622301/33a3a16d-cbcc-4910-91a9-8b3df912f0d9)
____

Why do those two buttons have different colors? Is one more important than the other?
![Screenshot at 2024-06-25 22-21-58](https://github.com/pi-hole/web/assets/26622301/0a792189-1fce-4e01-9869-5917dae85411)

___

If no app password is currently set, we should not show the button to remove it.
![Screenshot at 2024-06-25 22-22-40](https://github.com/pi-hole/web/assets/26622301/12e65283-29d1-49f9-a63a-bced9448a14e)

2024-06-25 21:31 UTC, rdwebdesign commented
### 1.
> On midnight and high contrast dark theme the cross is hard to see

Fixed.

### 2.

2024-06-26 06:04 UTC, yubiuser commented
> Actually, the app password is always generated when this modal is opened:

Mhh.. sure, it must be generated already to show it to the user. But is it already saved when the modal is opened?

2024-06-26 07:17 UTC, rdwebdesign commented
> But is it already saved when the modal is opened?

I'm not sure. Maybe @DL6ER can answer this question.

2024-06-26 08:58 UTC, DL6ER commented
> Mhh.. sure, it must be generated already to show it to the user. But is it already saved when the modal is opened?

Yes and No. It is only saved (and, hence, made active) once the user confirms this.

> Maybe someone else has an explanation for the colors.

`Enable 2FA` is green as it is "good" (as in: it enhances security, especially with very simple passwords). App passwords, on the other hand, are neutral in terms of security (as long as they are kept secret it's basically impossible to brute-force it due to its design complexity and a cryptographically secure source of randomness used to generate it).

2024-06-26 17:25 UTC, rdwebdesign approved these changes

2024-06-26 20:04 UTC, yubiuser approved these changes

2024-06-27 12:28 UTC, merged